require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - '**/binyo/**/*'

  Performance:
    Exclude:
      - '**/spec/**/*'

Metrics/LineLength:
  Max: 120
